import styles from './trustscore.module.css';

export default function TrustScorePage() {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Understanding the Trust Score</h1>
      
      <div className={styles.content}>
        <section>
          <h2>What is the Trust Score?</h2>
          <p>
            The Trust Score is a credibility rating assigned to each article submitted on NewsGrid. It ranges from 0 to 100 and is designed to give you a quick, at-a-glance understanding of an article's likely reliability based on a comprehensive AI-powered analysis.
          </p>
        </section>

        <section>
          <h2>How is the Score Calculated?</h2>
          <p>
            Our Trust Score is generated by a sophisticated AI model that performs a multi-faceted analysis of the article. The key factors it considers include:
          </p>
          <ul>
            <li><strong>Source Analysis:</strong> The AI examines the provided sources for credibility, relevance, and corroboration. It checks if the sources are reputable and if they actually support the claims made in the article.</li>
            <li><strong>Content Verification:</strong> The AI cross-references the main claims and facts presented in the article against a broad index of information on the web to check for factual accuracy and consistency.</li>
            <li><strong>Tone and Bias Detection:</strong> The system analyzes the language of the article to detect potential bias, sensationalism, or emotionally charged language that might undermine objectivity.</li>
            <li><strong>Structural Integrity:</strong> The AI looks for logical consistency, well-reasoned arguments, and a clear distinction between factual reporting and opinion.</li>
          </ul>
          <p>
            Based on this analysis, the AI generates a detailed report and calculates a final score.
          </p>
        </section>

        <section>
          <h2>What Do the Scores Mean?</h2>
          <ul>
            <li><strong>80-100 (High Confidence):</strong> Articles in this range are typically well-sourced, factually accurate, and written in an objective tone. The claims are well-supported by credible evidence.</li>
            <li><strong>60-79 (Medium Confidence):</strong> These articles may be largely accurate but might have some weaknesses, such as relying on fewer sources, minor inconsistencies, or hints of biased language.</li>
            <li><strong>40-59 (Low Confidence):</strong> Articles with this score often have significant issues, such as poor sourcing, unsubstantiated claims, or biased and opinionated language. Readers should approach these articles with caution.</li>
             <li><strong>0-39 (Very Low Confidence):</strong> Scores in this range indicate major credibility problems. The article may contain misinformation, lack credible sources entirely, or exhibit extreme bias.</li>
          </ul>
        </section>

        <section className={styles.disclaimer}>
          <h2>An Important Disclaimer</h2>
          <p>
            The Trust Score is a powerful tool, but it is not infallible. It is intended to be a helpful guide, not a definitive judgment. We encourage you to use the score as a starting point for your own critical thinking and to always read articles with a discerning eye.
          </p>
        </section>
      </div>
    </div>
  );
}
